-- 코드를 입력하세요
WITH FILTERED AS (
    SELECT
        CAR_ID,
        MONTH(START_DATE) AS MONTH
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
),
CAR_COUNT AS (
    SELECT 
        CAR_ID,
        COUNT(*) AS TOTAL_COUNT
    FROM FILTERED
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
)
SELECT
    f.MONTH,
    f.CAR_ID,
    COUNT(*) AS RECORDS
FROM FILTERED f
JOIN CAR_COUNT cc
  ON f.CAR_ID = cc.CAR_ID
GROUP BY f.MONTH, f.CAR_ID
HAVING COUNT(*) > 0
ORDER BY f.MONTH ASC, f.CAR_ID DESC;